### PR TITLE
Change media file get function and add status column

### PR DESCRIPTION
**Pull request by ninthday**
- Changed file_get_contents function to curl for more security
- Add Status column in the media table to save http status

### CODE REVIEW

**Comment by ninthday** [comment]
I change media file get function and add status column to the media table.

**Comment by dentoir** [comment]
Hi @ninthday 

Thanks for your contribution. However, I can't merge this yet as I don't want to add the status column to the media table on the fly. I'd prefer to use the standard upgrade path which is defined in common/upgrade.php. 

If you're willing to work on this again, that'd be great. I'll be back the first week of January to merge any code.

**Comment by ninthday** [comment]
Hi, @dentoir 

Thank you for your suggestion. 
Because I did not save all bin's media, so add the status column only in bin_media which we needed. I will look at `common/upgrade.php` during this time.
Thanks again and wish you a happy holiday~

**Comment by niczem** [comment]
I close this PR because there haven't been any updates since 2017. Please reopen if this PR still should be merged.

**Pull request closed without merging**
