### PR TITLE
REST API for purging tweets

### PR DESCRIPTION
**Pull request by hoylen**
This pull request contains a new RESTful API for purging tweets from the database. This can be used to reduce the database size after tweets have been exported or are no longer required. A few other RESTful functions are provided to support automating the purging: namely an API to list the names of the query bins.

The branch of this pull request can be installed for testing using:

    ./tcat-install-linux.sh -R https://github.com/hoylen/dmi-tcat.git -B restful-api  -l -c myconfig.cfg

**Resources and operations**

REST identifies each "resource" with a URI and a small vocabulary of operations on those resources. There are three resources: all query bins, a specific query bin, and the tweets of a specific query bin. The operations are:

- Sending a HTTP GET request to _http://hostname/api/querybin.php_ shows a list of all the query bins.

- Sending a HTTP GET request to _http://hostname/api/querybin.php/binName_ shows some information about the named query bin.

- Sending a HTTP GET request to _http://hostname/api/querybin.php/binName/tweets_ shows some information about the tweets in the named query bin. The tweets can be constrained by time using URL query parameters. For example, _http://<hostname>/api/querybin.php/tweets?startdate=2016-05-24+11%3A23%3A00+UTC&enddate=2016-06-04+04%3A04%3A34+UTC_ shows information about the tweets captured between (and equal) to the `startdate` and `enddate`. If only `enddate` is provided, all tweets from the first up to and including that end time are included. If only `startdate` is provided, all tweets from and including that start time to the last tweet are included. If neither are provided, all tweets are included.

- Sending a HTTP DELETE request to  _http://hostname/api/querybin.php/binName/tweets_ purges the tweets. The `startdate` and `enddate` URL query parameters can be used to select which tweets to purge (and behave the same as in the GET request).

   Since Web browsers can't send HTTP DELETE requests, a HTTP POST request with an extra URL query parameter of `action=purge-tweets` also invokes this operation.

Considerable effort has been spent in getting timezones to behave correctly, and to be clear and usable by the user. Time parameters can include an explicit timezone value, or will default to the timezone configured in _api/lib/common.php_. Initially, no default timezone is configured, so times must include an explicit timezone. When times are displayed, the timezone is always explicitly shown to avoid confusion. When displayed on a Web page, hovering the pointer over the text will also show the time in UTC.

Note: by configuring Apache, it should be possible to remove the ".php" from those URLs, making it look more clean and REST-like. This has not been tested, but it is expected that the scripts will work without modification.

**Representations**

REST supports different representations:

- When the above is performed in a Web browser, HTML is produced.
- When the above is performed by a HTTP client that is not a Web browser, JSON is produced.

More specifically, this is controlled by the "Accept" header in the HTTP request. For example:

    curl -H "Accept: application/json" -u admin:<password> http://<hostname>/api/querybin.php

With curl, explicitly asking for "application/json" is unnecessary, since curl's default is "Accept: \*/\*" and JSON is the default media type for that operation. A normal Web browser usually includes "text/html" in preference to "\*/\*" in its accept header, which is why HTML is returned to them.

**Command line**

The script can also be invoked from the command line. For details, run:

    php /var/www/dmi-tcat/api/querybin.php --help

The command line options allow it to run in different ways, to access the different functions available through the HTTP API.

Note: ISO 8601 format dates with a "T" to separate the date from the time (e.g. "2016-06-06T17:10+05:45") are accepted by the Web form, URI query parameters and the command line. It is especially useful on the command line, since it avoids having a space in the date-time value.

**Known limitations**

- The tcat_* tables are not modified when tweets are purged, so the original capture periods remain. After purging tweets, it will appear as if the capture(s) were performed but no tweets appeared.

  A future enhancement could be to also purge/update the tcat_* tables. Then, after purging tweets, it will appear as if the capture(s) were never performed.

- The purging operation is the same for all capture modes (i.e. track, follow, one-percent). From what I can tell, the table structure is exactly the same, so this should be correct.

P.S. The _analysis/common/functions.php_ file was modified so it will not fail when there are no tables in the database (i.e. after installation, but before the capture page is visited) or when no query bins have been created.

### CODE REVIEW

**Comment by hoylen** [comment]
Done some more testing. It should be noted that purging _all_ the tweets (i.e. with no start time and no end time specified) is very quick. But if there are many tweets and either/both a start/end time is specified, tweet purging can be extremely slow.

This limitation is partially due to the *_media, *_palces, and *_withheld tables not having a copy of the `created_at` column, and a join with the *_tweets table is needed to work out which rows can be deleted. But even a simple `DELETE FROM table_name WHERE "..." < created_at;` just takes an extremely long time when there are millions of rows involved.

So the purge-tweets feature is only practical if you are going to purge all tweets; or the total number of tweets in the tables is kept low by frequently purging them.

**Comment by hoylen** [comment]
From testing, a rough estimate of how long it takes to purge tweets is:

    seconds_taken = number_of_total_tweets x number_of_tweets_deleted x 0.0000000175

Obviously, this will vary depending on how fast the computer is, etc.

To purge 9,900 tweets from 10,000 tweets will take about 1.7 seconds.
To purge 9,900 tweets from 100,000 tweets will take 17 seconds.
To purge 99,900 tweets from 100,000 tweets will take 174.8 seconds:  3 minutes.
To purge 9,900 tweets from 1,000,000 tweets takes about 3 minutes.
To purging 999,900 tweets from 1,000,000 tweets will take about 5 hours.

If all the tweets are purged (i.e. no start or end time specified) then it only takes a few seconds, regardless of how many tweets there are.

**Comment by brendam** [comment]
@dentoir any idea when this will be merged? Is there anything I can do to help make that happen?

**Comment by dentoir** [comment]
I'm testing this now.

**Comment by dentoir** [comment]
The new code seems to work well and I tested it in the cloud and on our own servers. On my personal laptop, I noticed `$_SERVER['PATH_INFO']` was undefined, preventing the API code-parts from functioning. This is probably caused by some non-standard Apache configuration on the laptop, as the variable is present in a vanilla Apache installation. This is for future reference, if someone else encounters the same problem.

**Pull request merged**
