### PR TITLE
Phrases must not exceed 60chrs each

### LINKED ISSUE #334: Long conjunctive query phrases make TCAT not start
Hi. The following, long conjunctive query phrase `#Chinabigbrother #Citizenrating #Chinasurveillance #Socialcredit #Chinablackmirror #Digitaldictatorship #Digitalcensorship #Socialcreditsystem` will make TCAT not restart after the routine reload which is performed shortly after a query bin is added, as observed in `logs/controller.php`

> 2018-09-30 19:38:02	enforcing reload of config for track
2018-09-30 19:38:02	sending a TERM signal to track for 10060
2018-09-30 19:38:02	waiting for graceful exit of script track with pid 10060

I am waiting for the process `dmitcat_track.php` to respawn via the normal cronjob by monitoring its appearance in `ps afx |grep 'var/www/dmi-tcat' |grep "track"` listing. It won't be there. Removing the bin from the usual web UI brings the `dmitcat_track.php` back, after the routine reload is done (in a dozen or so seconds).

screen shot 2018-09-30 at 19 52 08

The query phrase is long, 142 characters. If I arbitrarily split it into two by placing a disjuctive comma in the middle `#Chinabigbrother #Citizenrating #Chinasurveillance #Socialcredit, #Chinablackmirror #Digitaldictatorship #Digitalcensorship #Socialcreditsystem` the same issue still persists.

However, if I further split these into two disjunctions each, `#Chinabigbrother #Citizenrating, #Chinasurveillance #Socialcredit, #Chinablackmirror #Digitaldictatorship, #Digitalcensorship #Socialcreditsystem`, things work as usual. Of course any actual query design is out the window by this point (if it ever was there, but that's an another matter).

I observed the unabridged query phrase go into the database. The bin gets it's entries in `tcat_query_bins_*` tables, as usual.

I am not particularly expert in PHP / SQL webapp debugging, so if someone can please guide me how to get more information about the program flow, where to request debug messages, throw PHP exceptions and stack traces, or maybe even run the `dmitcat_track.php` under [XDebug](https://xdebug.org/) or another debugging tool, I would appreciate it.

I hope I will be able the send a pull request once I have a better idea where to get more information what goes wrong.

### PR DESCRIPTION
**Pull request by xmacex**
I believe this fixes #334. In general I do not feel very confident about this PR, but I want to contribute 😄 . I hope someone more familiar with the TCAT codebase reviews this PR. Comments are of course welcome, and I'll do my best to incorporate them.

I provide a couple of tests for this under a new top-level directory *tests*. There is an element of danger here, if the tests are run on a live TCAT installation where test data might trickle down to the database. Some [PHPUnit database setup and fixtures](https://phpunit.readthedocs.io/en/7.3/database.html) ought to used to insulate these tests from live data.

Sorry I could not provide tests for the UI check and in Javascript function `validateQuery(query,type)` For my own purposes, I isolated the function into `validateQuery.js` and my test suite with [Jest](https://jestjs.io/) is the following `package.json`

```json
{
    "dependencies": {
	"jquery": "^3.3.1"
    },
    "scripts": {
	"test": "jest"
    },
    "jest": {
    }
}
```

this `jest.config.js`

```js
module.exports = {
    setupFiles: ["<rootDir>/test-env.js"],
    testEnvironmentOptions: {
	beforeParse (window) {
	    console.log('------------------ window.alerts')
	    window.alert = (msg) => {console.log(msg); };
	}
    }
}
```

and the following `validateQuery.test.js`

```js
const validateQuery = require('./tcat-validateQuery');

test('Perfectly fine, straightforwards track query should validate', () => {
    expect(validateQuery('kittens,lizards,aardvark', 'track')).toBe(true);
});

describe('Check commas in places', () => {
    test('Track query beginning with a comma should validate', () => {
	expect(validateQuery(',kitten,lizard,aardvark', 'track')).toBe(true);
    });

    test('Track query ending in a comma should validate', () => {
	expect(validateQuery('kitten,lizard,aardvark,', 'track')).toBe(true);
    });

    test('Track query with repeated commas should validate', () => {
	expect(validateQuery('kitten,,,,lizard,aardvark', 'track')).toBe(true);
    });

    test('Track query with commas inside literals should not validate', () => {
	expect(validateQuery("kitten,'lizard,queen',aardvark", 'track')).toBe(false);
    });
});

describe('Check query phrase lenghts', () => {
    test('Empty track query should not validate', () => {
	expect(validateQuery('', 'track')).toBe(false);
    });

    test('Long total query with short enough phrases should validate', () => {
	expect(validateQuery('kitten,lizard,aardvark,doggo,anteater,snake,wombat,vampire bat,zebra,moose,ruutana', 'track')).toBe(true);
    });
    
    test('Track query with a phrase 60 chrs long phrase should validate', () => {
	expect(validateQuery('kitten,lizard,aarvark,012345678901234567890123456789012345678901234567890123456789', 'track')).toBe(true);
    });

    test('Track query phrase over 60 chrs long phrase should not validate', () => {
	expect(validateQuery('kitten,lizard,aarvark,012345678901234567890123456789012345678901234567890123456789aaaaaaaaaaaaaaaaaaaaa', 'track')).toBe(false);
    });
});
```

And then `npm test` yields

> PASS  ./tcat-validateQuery.test.js
>   ✓ Perfectly fine, straightforwards track query should validate (7ms)
>   Check commas in places
>     ✓ Track query beginning with a comma should validate (1ms)
>     ✓ Track query ending in a comma should validate
>     ✓ Track query with repeated commas should validate
>     ✓ Track query with commas inside literals should not validate (1ms)
>   Check query phrase lenghts
>     ✓ Empty track query should not validate
>     ✓ Long total query with short enough phrases should validate (1ms)
>     ✓ Track query with a phrase 60 chrs long phrase should validate
>     ✓ Track query phrase over 60 chrs long phrase should not validate
> 
> ------------------ window.alerts
> Imported jQuery version 3.3.1 in test-env.js
> Single quotes can only be used to specify a literal query without comma's. Please change your query.
> You should specify at least one query
> Query phrases should not exceed 60 characters each. Please shorten your query phrases.
> Test Suites: 1 passed, 1 total
> Tests:       9 passed, 9 total
> Snapshots:   0 total
> Time:        6.33s
> Ran all test suites.

### CODE REVIEW

**Comment by xmacex** [comment]
Any change of someone reviewing this? :)

**Comment by xmacex** [comment]
I've implemented checks against the 60 character limit per query in `common/functions.php` function validate_capture_phrases()`, as requested in https://github.com/digitalmethodsinitiative/dmi-tcat/issues/334#issuecomment-437837800. Now that I think about it, I was making some assumptions where it will be employed in the application... 🤔. I better check those assumptions...

**Comment by xmacex** [comment]
Ok phew my assumptions were not ludicrous.

```sh
howdonamesevenwork:dmi-tcat $ find . -name '*.php' -exec egrep -l 'validate_capture_phrases' \{\} \;;
./capture/search/search.php
./tests/common/functionsTest.php
./common/functions.php
howdonamesevenwork:dmi-tcat $
```

Of which the last one only has its definition, the second one is in the test suite. As things currently stand, the only occurrence of calling it is https://github.com/digitalmethodsinitiative/dmi-tcat/blob/09e31a9f9da784376dcbdc97784f6e8553730623/capture/search/search.php#L34

**Comment by xmacex** [comment]
Whoops I notice a merge conflict has appeared 👀.

**Comment by niczem** [comment]
"Whoops I notice a merge conflict has appeared 👀. Was it always there?"

... the trim function was replaced by the sanitise function in between. I resolved the conflict.

Sorry for the long silence, we are currently cleaning up the repo and hope to merge open pull requests as soon as possible :)

**Pull request merged**
